version: "3.8"

services:
   mysql:
     image: mysql:8
    #  command: --default-authentication-plugin=mysql_native_password
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: nest
      #  MYSQL_USER: root
     ports:
       - "3306:3306"